[package]
name = "yrs-client"
version = "0.1.0"
edition = "2021"
description = "Yrs test client"
license = "MIT"
authors = ["Carlos Herrero"]

[dependencies]
lib0 = "0.12"
yrs = "0.12"
yrs-warp = "0.2"
warp = "0.3"
tokio = { version = "1.20", features = ["full"] }
